server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: clientes
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://mysql_db:3306/dbclientes?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: admin
    password: admin

---
spring:
  application:
    name: clientes
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect 
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
